/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package corn_test.petstore_test;

import corn_test.petstore_test.utils.HTTPClient;

class SDKConfiguration {
	public HTTPClient defaultClient;
	public HTTPClient securityClient;
	
	public String serverUrl;
	public int serverIdx = 0;
	public String language = "java";
	public String openapiDocVersion = "1.0.0";
	public String sdkVersion = "1.0.0";
	public String genVersion = "2.43.2";
	
}