/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package corn_test.petstore_test.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class ShowPetByIdResponse {
    
    public String contentType;

    public ShowPetByIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * unexpected error
     */
    
    public corn_test.petstore_test.models.shared.Error error;

    public ShowPetByIdResponse withError(corn_test.petstore_test.models.shared.Error error) {
        this.error = error;
        return this;
    }
    
    /**
     * Expected response to a valid request
     */
    
    public corn_test.petstore_test.models.shared.Pet[] pets;

    public ShowPetByIdResponse withPets(corn_test.petstore_test.models.shared.Pet[] pets) {
        this.pets = pets;
        return this;
    }
    
    
    public Integer statusCode;

    public ShowPetByIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ShowPetByIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public ShowPetByIdResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
